// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTUDTMDT.Models;

#nullable disable

namespace PTUDTMDT.Migrations
{
    [DbContext(typeof(PtudtmdtContext))]
    [Migration("20241215055103_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietTuKhoa", b =>
                {
                    b.Property<string>("MaTuKhoa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTuKhoa", "MaSanPham")
                        .HasName("PK__ChiTietT__EE76E12A5BC03125");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietTuKhoa", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.ChiTietDonHang", b =>
                {
                    b.Property<string>("MaCtdh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaCTDH");

                    b.Property<double?>("GiaSanPham")
                        .HasColumnType("float");

                    b.Property<string>("MaDonHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayTaoDon")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double?>("TongTienSp")
                        .HasColumnType("float")
                        .HasColumnName("TongTienSP");

                    b.HasKey("MaCtdh")
                        .HasName("PK__ChiTietD__1E4E40F08902BDFD");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.DanhGiaSanPham", b =>
                {
                    b.Property<string>("MaDanhGia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LoiDanhGia")
                        .HasColumnType("text");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SaoDanhGia")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DanhGiaS__AA9515BFFF00F673");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DanhGiaSanPham", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.DiaChi", b =>
                {
                    b.Property<string>("MaDiaChi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChuanHoaUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ChuanHoaURL");

                    b.Property<string>("TenDiaChi")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TheLoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ViTriNha")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaDiaChi")
                        .HasName("PK__DiaChi__EB61213EB2E77E0F");

                    b.ToTable("DiaChi", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.DonHang", b =>
                {
                    b.Property<string>("MaDonHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaGiaoHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaPttt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaPTTT");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayLenDon")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("TtthanhToan")
                        .HasColumnType("bit")
                        .HasColumnName("TTThanhToan");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584AD29855D08");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaGiaoHang");

                    b.HasIndex("MaPttt");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.GiamGium", b =>
                {
                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("GiaTri")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMa")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaGiamGia")
                        .HasName("PK__GiamGia__EF9458E4AA88837B");

                    b.ToTable("GiamGia");
                });

            modelBuilder.Entity("PTUDTMDT.Models.GiaoHang", b =>
                {
                    b.Property<string>("MaGiaoHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CongTyGiaoHang")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenShipper")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaGiaoHang")
                        .HasName("PK__GiaoHang__81CCF4FDB618EB53");

                    b.ToTable("GiaoHang", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool?>("HieuLuc")
                        .HasColumnType("bit");

                    b.Property<string>("Hinh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaDiaChi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E512C2EC18");

                    b.HasIndex("MaDiaChi");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.LoaiSanPham", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Hinh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSanP__730A5759B65DC646");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<string>("MaPttt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaPTTT");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<string>("TenPttt")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenPTTT");

                    b.HasKey("MaPttt")
                        .HasName("PK__PhuongTh__B30A2802D873866F");

                    b.ToTable("PhuongThucThanhToan", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("BestSellers")
                        .HasColumnType("bit");

                    b.Property<double?>("GiaSanPham")
                        .HasColumnType("float");

                    b.Property<double?>("GiaSauGiam")
                        .HasColumnType("float");

                    b.Property<double?>("GiamGia")
                        .HasColumnType("float");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime");

                    b.Property<string>("Hinh1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Hinh2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("HomeFlag")
                        .HasColumnType("bit");

                    b.Property<string>("MaLoai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySanXuat")
                        .HasColumnType("datetime");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("text");

                    b.Property<int?>("SltonKho")
                        .HasColumnType("int")
                        .HasColumnName("SLTonKho");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("TinhTrang")
                        .HasColumnType("bit");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442D4F1599F6");

                    b.HasIndex("MaLoai");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LanCuoiTruyCap")
                        .HasColumnType("datetime");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayTaoTk")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTaoTK");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("TinhTrangTk")
                        .HasColumnType("bit")
                        .HasColumnName("TinhTrangTK");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C6529E99E0A11");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.TrangViet", b =>
                {
                    b.Property<string>("MaTrangViet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Alias")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<string>("TenTrangViet")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ThoiGianDang")
                        .HasColumnType("datetime");

                    b.Property<string>("Thumb")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TuKhoa")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("URL");

                    b.HasKey("MaTrangViet")
                        .HasName("PK__TrangVie__6DAAED94C37D6D69");

                    b.ToTable("TrangViet", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.TrangWeb", b =>
                {
                    b.Property<string>("MaTrangWeb")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenTrangWeb")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("URL");

                    b.HasKey("MaTrangWeb")
                        .HasName("PK__TrangWeb__F3C8EBD84E5F3189");

                    b.ToTable("TrangWeb", (string)null);
                });

            modelBuilder.Entity("PTUDTMDT.Models.TuKhoa", b =>
                {
                    b.Property<string>("MaTuKhoa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenTuKhoa")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaTuKhoa")
                        .HasName("PK__TuKhoa__21DA9568A6020086");

                    b.ToTable("TuKhoa", (string)null);
                });

            modelBuilder.Entity("ChiTietTuKhoa", b =>
                {
                    b.HasOne("PTUDTMDT.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("ChiTietTuKhoa_masanpham");

                    b.HasOne("PTUDTMDT.Models.TuKhoa", null)
                        .WithMany()
                        .HasForeignKey("MaTuKhoa")
                        .IsRequired()
                        .HasConstraintName("ChiTietTuKhoa_matukhoa");
                });

            modelBuilder.Entity("PTUDTMDT.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("PTUDTMDT.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("chitietdonhang_madonhang");

                    b.HasOne("PTUDTMDT.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("chitietdonhang_masanpham");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("PTUDTMDT.Models.DanhGiaSanPham", b =>
                {
                    b.HasOne("PTUDTMDT.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("danhgiasanpham_masanpham");

                    b.HasOne("PTUDTMDT.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaTaiKhoan")
                        .HasConstraintName("danhgiasanpham_mataikhoan");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("PTUDTMDT.Models.DonHang", b =>
                {
                    b.HasOne("PTUDTMDT.Models.GiamGium", "MaGiamGiaNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaGiamGia")
                        .HasConstraintName("donhang_magiamgia");

                    b.HasOne("PTUDTMDT.Models.GiaoHang", "MaGiaoHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaGiaoHang")
                        .HasConstraintName("donhang_magiaohang");

                    b.HasOne("PTUDTMDT.Models.PhuongThucThanhToan", "MaPtttNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaPttt")
                        .HasConstraintName("donhang_mapttt");

                    b.HasOne("PTUDTMDT.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaTaiKhoan")
                        .HasConstraintName("donhang_mataikhoan");

                    b.Navigation("MaGiamGiaNavigation");

                    b.Navigation("MaGiaoHangNavigation");

                    b.Navigation("MaPtttNavigation");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("PTUDTMDT.Models.KhachHang", b =>
                {
                    b.HasOne("PTUDTMDT.Models.DiaChi", "MaDiaChiNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaDiaChi")
                        .HasConstraintName("khachhang_madiachi");

                    b.Navigation("MaDiaChiNavigation");
                });

            modelBuilder.Entity("PTUDTMDT.Models.SanPham", b =>
                {
                    b.HasOne("PTUDTMDT.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("sanpham_maloai");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("PTUDTMDT.Models.TaiKhoan", b =>
                {
                    b.HasOne("PTUDTMDT.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("taikhoan_makhachhang");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("PTUDTMDT.Models.DiaChi", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("PTUDTMDT.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("PTUDTMDT.Models.GiamGium", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("PTUDTMDT.Models.GiaoHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("PTUDTMDT.Models.KhachHang", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("PTUDTMDT.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("PTUDTMDT.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("PTUDTMDT.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGiaSanPhams");
                });

            modelBuilder.Entity("PTUDTMDT.Models.TaiKhoan", b =>
                {
                    b.Navigation("DanhGiaSanPhams");

                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
